# Generated by Django 3.2.6 on 2021-12-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('squad', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='espnapp.players')),
            ],
        ),
    ]
