# Generated by Django 3.2.6 on 2021-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squads',
            name='series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='squads',
            name='squad',
        ),
        migrations.AddField(
            model_name='squads',
            name='squad',
            field=models.ManyToManyField(to='espnapp.Players'),
        ),
    ]
